Took the latest version from ctags source repository, because the one we
	* tagmanager/c.c: Took the latest version from ctags source
	repository, because the one we had (from ctags 5.6) was broken.

	* global_tags/create_global_tags.sh.in: Reverted the patch from
	Sylvain because it was not right fix (and added a helpful comment).
	Used /bin/bash to fix the bashism and generated separate log files
	for each tag files in the same directory.

diff --git a/global-tags/create_global_tags.sh.in b/global-tags/create_global_tags.sh.in
--- a/global-tags/create_global_tags.sh.in
+++ b/global-tags/create_global_tags.sh.in
@@ -1,89 +1,92 @@
-#!/bin/sh
+#!/bin/bash
 
-PKG_CONFIG=`which pkg-config 2>/dev/null`
-if [ "x$PKG_CONFIG" = x -o ! -x "$PKG_CONFIG" ]
-then
-    echo "Can not find or execute pkg-config" >&2
-    exit 1
-fi
-
-ANJUTA_TAGS="@scriptdir@/anjuta-tags"
-if [ ! -x "$ANJUTA_TAGS" ]
-then
-    echo "Can not execute $ANJUTA_TAGS" >&2
-    exit 1
-fi
-
-echo "[...........................................................................]"
-echo "[. Generating System tags. This may take several minutes (1 min to 20 mins).]"
-echo "[. You can go out, have a coffee and return back in 20 mins. ...............]"
-echo "[...........................................................................]"
-
-ANJUTA_DIR="$HOME/.anjuta"
-if [ ! -d "$ANJUTA_DIR/tags" ]
-then
-    mkdir -p "$ANJUTA_DIR/tags"
-    if [ ! -d "$ANJUTA_DIR/tags" ]
-    then
-        echo "Can not create $ANJUTA_DIR/tags" >&2
-        exit 1
-    fi
-fi
-
-verbose=no
-for package in `"$PKG_CONFIG" --list-all|cut -f1 '-d '` ;
-do
-    cflags=`"$PKG_CONFIG" --cflags "$package" 2>/dev/null`
-    tag_file="$ANJUTA_DIR/tags/$package.anjutatags"
-    echo "  . Creating tags file: $package.anjutatags.gz ..."
+function anjuta_tags {
 
     FILES=""
-    for cflag in $cflags ;
-    do
-        case "$cflag" in
-            -I/usr/include)
-            ;;
-            -I/usr/local/include)
-            ;;
-            -I*)
-                include=`echo "$cflag"|sed 's/^-I//'`
-                if [ -d "$include" ]
-                then
-                    files=`find "$include" -name '*.h'`
-                    if [ "x$files" != x ]
-                    then
-                        if [ "x$FILES" != x ]
-                        then
-                            FILES="$FILES $files"
-                        else
-                            FILES="$files"
-                        fi
-                    fi
-                fi
-            ;;
-            *)
-            ;;
-        esac
-    done
-
-    rm -f "$tag_file" "$tag_file.gz"
-    if [ "x$FILES" != x ]
-    then
-        if [ "x$verbose" = xyes ]
-        then
-            FILES_COUNT=`echo "$FILES"|wc -w`
-            echo "    . Creating $tag_file"
-            echo "    . Number of files to scan: $FILES_COUNT"
-            echo "    . Files to scan: $FILES"
-        fi
-
-        CTAGS="$ctags" "$ANJUTA_TAGS" "$tag_file" $FILES 2>/dev/null
-        if [ ! -e "$tag_file" ]
-        then
-            echo "  WARNING: Could not create tags file: $tag_file" >&2
-        else
-            gzip -f "$tag_file"
-        fi
+    BASEDIR=`pwd`
+    PROGDIR=. # `dirname $0`
+    CFLAGS=""
+    ANJUTA_TAGS_BIN="@scriptdir@/anjuta-tags"
+    OUTPUT_FILE=$1
+    shift
+    
+    if [ -x "$ANJUTA_TAGS_BIN" ]
+	then
+	for cflag in $*
+	  do
+	  infile=`echo $cflag | sed 's/^-I//'`
+	  if [ -d "$infile" -a "$infile" != "/usr/include" -a "$infile" != "/usr/local/include" ]
+	      then
+	      FILES="$FILES \"$infile/*.h\" \"$infile/*/*.h\" \"$infile/*/*/*.h\""
+	  elif [ ! -d "$infile" -a -e "$infile" ]
+	      then
+	      FILES="$FILES $infile"
+	  fi
+	done
+    else
+	echo "Can not execute $ANJUTA_TAGS_BIN"
+	exit 1
     fi
-done
-echo "This is just a timestamp" > "$ANJUTA_DIR/system-tags.cache"
+    CFLAGS="$CFLAGS $*"
+    export CFLAGS
+    
+    FILES_COUNT=`echo $FILES | wc -w`
+    
+    echo "Creating $OUTPUT_FILE"
+    echo "Number of files to scan: $FILES_COUNT"
+    echo "Files to scan: $FILES"
+    
+    if [ $FILES_COUNT -gt 0 ] ; then
+	rm -f $OUTPUT_FILE
+	$ANJUTA_TAGS_BIN $OUTPUT_FILE $FILES 2>"$OUTPUT_FILE.log"
+	
+    # If global tags file could not be generated
+	if [ ! -e $OUTPUT_FILE ] ; then
+	    echo "WARNING: Could not create tags file $OUTPUT_FILE!" >&2
+	else
+	    gzip -f $OUTPUT_FILE
+	fi
+    fi
+}
+
+## FILES="\"/usr/include/*.h\" \"/usr/local/include/*.h\""
+FILES=""
+BASEDIR=`pwd`
+PROGDIR=. # `dirname $0`
+CFLAGS=""
+ANJUTA_TAGS="anjuta_tags"
+
+
+echo "Generating System tags..."
+
+mkdir -p "$HOME/.anjuta/tags"
+
+# pkg-config libraries
+PKG_CONFIG=`which pkg-config 2>/dev/null`
+if ( [ ! -z $PKG_CONFIG ] && [ -x $PKG_CONFIG ] ) ; then
+    ##
+	## We are scaning .pc files directly because --cflags option
+	## produces include paths and flags for other packages depended by
+	## the packages, which we don't like. We only want cflags relevent
+	## to the packages alone.
+	##
+    PKG_DEFAULT_CONFIG_PATH=`echo $PKG_CONFIG | sed -e 's/\/bin\/pkg-config/\/lib\/pkgconfig'/`
+    PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PKG_DEFAULT_CONFIG_PATH"
+    PKG_DEFAULT_CONFIG_PATH=`echo $PKG_CONFIG | sed -e 's/\/bin\/pkg-config/\/lib64\/pkgconfig'/`
+    PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PKG_DEFAULT_CONFIG_PATH"
+	
+    PKG_CONFIG_PATH_PROPER=`echo $PKG_CONFIG_PATH | sed -e 's/\:/ /g'`
+    for pkg_path in $PKG_CONFIG_PATH_PROPER; do
+	for pkg_file in $pkg_path/*.pc; do
+		# echo "Scanning package: $pkg_file"
+	    PKG_CFLAGS=`cat $pkg_file  2>/dev/null | grep -e "^\(\w\+\=\|\s*Cflags\:\)" | sed -e "s/^\s*Cflags\:\(.*\)/echo \"\1\"/" | sed -e 's/^\(\w\+\)\=\(.*\)/\1\=\"\2\"/' | sh`
+		# echo $PKG_CFLAGS
+	    package=`echo $pkg_file | sed -e 's/^.*\/\(.*\)\.pc/\1/'`
+	    # if [ ! -e $BASEDIR/tags/$package.anjutatags.gz ] ; then
+		echo "Creating tags file: $HOME/.anjuta/tags/$package.anjutatags.gz ..."
+		anjuta_tags "$HOME/.anjuta/tags/$package.anjutatags" $PKG_CFLAGS > /dev/null
+	    # fi
+	done
+    done
+    echo "This is just a timestamp" > $HOME/.anjuta/system-tags.cache
+fi
